// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarController from "./avatar_controller"
application.register("avatar", AvatarController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationSubscriptionController from "./notification_subscription_controller"
application.register("notification-subscription", NotificationSubscriptionController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)

import UserMenuTabController from "./user_menu_tab_controller"
application.register("user-menu-tab", UserMenuTabController)
